name: hospital-dev

services:
  postgres:
    extends:
      file: ./docker-compose.base.yml
      service: postgres
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env.dev

  redis:
    extends:
      file: ./docker-compose.base.yml
      service: redis
    ports:
      - 6379:6379
    env_file:
      - ./backend/.env.dev

  rabbitmq:
    extends:
      file: ./docker-compose.base.yml
      service: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ./backend/.env.dev

  zookeeper:
    extends:
      file: ./docker-compose.base.yml
      service: zookeeper
    ports:
      - 2181:2181
    env_file:
      - ./backend/.env.kafka

  kafka:
    extends:
      file: ./docker-compose.base.yml
      service: kafka
    ports:
      - 9092:9092
      - 9997:9997
      - 29092:29092
      - 29095:29095
    depends_on:
      - zookeeper:
          condition: service_started
    env_file:
      - ./backend/.env.kafka

  kafka_ui:
    extends:
      file: ./docker-compose.base.yml
      service: kafka_ui
    ports:
      - 8082:8080
    depends_on:
      - kafka:
          condition: service_started
    environment:
      DYNAMIC_CONFIG_ENABLED: true

  backend:
    extends:
      file: ./docker-compose.base.yml
      service: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
      - 5555:5555

  frontend:
    extends:
      file: ./docker-compose.base.yml
      service: frontend
    build:
      context: ./frontend
      dockerfile: ./docker/dev.Dockerfile
    ports:
      - 3000:3000

  redisinsight:
    extends:
      file: ./docker-compose.base.yml
      service: redisinsight
    ports:
      - 5540:5540
    env_file:
      - ./backend/.env.dev

networks:
  default-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  static_data:
  media_data:
  redisinsight_data: