services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default-network
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s

  redis:
    image: redis:7.4.0-alpine
    container_name: redis-service
    volumes:
      - redis_data:/data
    networks:
      - default-network
    restart: on-failure
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-service
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - default-network
    restart: on-failure
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 3s
      timeout: 10s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: zookeeper-service
    hostname: zookeeper
    networks:
      - default-network
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka-service
    hostname: kafka
    networks:
      - default-network
    restart: always

  kafka_ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui-service
    networks:
      - default-network
    restart: always

  frontend:
    container_name: frontend-service
    networks:
      - default-network
    restart: on-failure

  backend:
    container_name: backend-service
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    networks:
      - default-network
    restart: on-failure

  redisinsight:
    image: redis/redisinsight:2.54.0
    container_name: redisinsight-service
    volumes:
      - redisinsight_data:/db
    networks:
      - default-network
    restart: on-failure

networks:
  default-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  static_data:
  media_data:
  redisinsight_data:
