global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus.domain.ru']

  - job_name: flower
    static_configs:
      - targets: ['flower.domain.ru']

  - job_name: api
    static_configs:
      - targets: ['api.domain.ru']
